### ISSUE TITLE
Option to inherit interface documentation by default

### ISSUE THREAD

**Issue by RunDevelopment** [TypeStrong/typedoc#1498]
## Search Terms

inheritdoc, inherit documentation, configuration option

## Problem

Class methods/accessors/properties that implement interface members do not inherit the interface's documentation.

This very annoying because the reader has to click on the `Implementation of X` note to be able to read the documentation of class members.

IDEs like VSCode do not have this problem. They will display the interface's documentation for inherited members if the implementation doesn't define its own documentation.

<details>

Example: No documentation at definition site

![image](https://user-images.githubusercontent.com/20878432/107125967-37d0e500-68ad-11eb-842d-d2b485e28e3e.png)

But VSCode still displays documentation.

![image](https://user-images.githubusercontent.com/20878432/107125955-225bbb00-68ad-11eb-97a2-62292d1ac1fe.png)

</details>

The only current solution for this problem is to add a `/** @inheritDoc */` to all class members without documentation.

## Suggested Solution

Add a new configuration option that will add an implicit `@inheritDoc` if a class member does not define its own documentation.

At least, this is how the solution is supposed to behave. It may be implemented differently of course.

**Comment by Gerrit0** [comment]
I could have sworn we already did this... but apparently not... maybe I imagined it, or did it on a branch that never ended up getting merged.

**Comment by Gerrit0** [comment]
With 0.20.23 we do this by default, decided to treat this as a bug report since I was pretty sure we should have been doing this in the first place.

**Comment by RunDevelopment** [comment]
Wow. All of my issues fixed in record time! Thank you @Gerrit0!

**Comment by Gerrit0** [comment]
Please open a new issue rather than posting in an old one.

**Comment by frank-weindel** [comment]
@harrydehix Did you create a new issue for this? Otherwise I will!

**Comment by birkskyum** [comment]
This still appear to be a problem in version 0.24.8 - the docs from the interface doesn't follow into the class implementing it unless I add inheritDoc to every method

**Comment by Gerrit0** [comment]
Please open a new issue rather than posting in an old one.
