### ISSUE TITLE
projectDocuments in a `merge` entryPointStrategy site

### ISSUE THREAD

**Issue by alexprudhomme** [TypeStrong/typedoc#2801]
## Search terms
entryPointStrategy, merge, projectDocuments, documents

## Question

Hi, 

I am having trouble setting up projectDocuments for my typedoc site. 

I am building a Typedoc site with `"entryPointStrategy": "merge"`, that takes in two --json builded sites. Project documents work fine in the root Typedoc project. However if I try to add some in the two --json builded site, they don't show up. 

They seem to show up as "documents" in the json file so I am not sure what I am doing wrong. Before digging up further, is this something that is supported ?

**Comment by Gerrit0** [comment]
Yes, this is supported! I just pushed a [gh2801](https://github.com/Gerrit0/typedoc-packages-example/tree/gh2801) branch to typedoc-packages-example which demonstrates it (build with the advanced settings in the readme to replicate your JSON setup)

![image](https://github.com/user-attachments/assets/90689c2c-bf94-460e-88ed-24198d7431a5)

Note that the documents for sub-projects will show up within the module created for that project, not at the top level.

**Comment by alexprudhomme** [comment]
I see, thanks for the example. My problem was that I had his at the root typedoc (the one merging). and it was removing the projectDocuments. Dont know if this would count as a bug.

```
  "navigation": {
    "includeGroups": true
  },
```

**Comment by Gerrit0** [comment]
That repo has an old version of typedoc installed - before 0.27 categorization/grouping wasn't performed on merged projects, so yes, it won't work there.

**Comment by alexprudhomme** [comment]
Hi, I updated to the latest version and it still does not work. I have tried many setups and could not find one where I had categories/group + sub package documents. 

<img width="509" alt="image" src="https://github.com/user-attachments/assets/732c857d-426e-4b64-849c-ac947b19122d">

<img width="451" alt="image" src="https://github.com/user-attachments/assets/89f370b6-3222-4e3f-872e-3683db823f76">

**Comment by Gerrit0** [comment]
That's a bug! The group/category restoration code missed checking for documents, easy fix at least.

**Comment by alexprudhomme** [comment]
Thanks a lot ! I suppose this will be in 0.27.5 ?

**Comment by Gerrit0** [comment]
Yes, likely this weekend, there are a couple other issues I want to look at
