### ISSUE TITLE
Cannot find name 'Promise'. ( error)

### ISSUE THREAD

**Issue by jtraband** [TypeStrong/typedoc#327]
I am running 

typedoc --out ./docs --target ES6 --includeDeclarations  ./src

and I get a number of "Cannot find name 'Promise'." errors.  What am i missing?

I am using TypeDoc 0.5.1

**Comment by jonaskello** [comment]
Are you using TS 2.0 and specifying the `lib` option to something like `"lib": ["dom", "es2015"]` in `tsconfig.json`? Promise is part of the ES6 API and the typings/existence of that is controlled by this option. Seems like typedoc does not support this option yet. I am having the same problem with `Map` and `Set`.

**Comment by jtraband** [comment]
Exactly....

**Comment by larsduelfer** [comment]
Same problem here, but we are targetting ES5. Seems that happened since using @Types in an Angular 2 project.

**Comment by jonaskello** [comment]
This is related to #315. There was a fix merged to ignore the lib option in #308 which now makes it possible to run typedoc but since it does not pass along the lib option to the compiler the compiler cannot find the typings for ES6 API like Promise, Map, Set etc.

**Comment by jtraband** [comment]
So is there a workaround, or do we just wait....?

**Comment by jtraband** [comment]
ok, workaround for now is to have the tsconfig have a target of 'es6' when generating files with TypeDoc.  So basically using a different tsconfig for typeDoc then for actual code generation.

**Comment by moshmage** [comment]
This is still happening, even when targeting ES6:

```logatlk
$ typedoc --mode modules --out ./docx/ --target "ES6" src/

Using TypeScript 2.0.6 from c:\Users\Mosh Mage\AppData\Roaming\npm\node_modules\typedoc\node_modules\typescript\lib
Error: c:/Users/Mosh Mage/WebstormProjects/rxjs-SocketIO-client/node_modules/rxjs/Observable.d.ts(67)
 Cannot find name 'Promise'.
Error: c:/Users/Mosh Mage/WebstormProjects/rxjs-SocketIO-client/node_modules/rxjs/Observable.d.ts(67)
 Cannot find name 'Promise'.
```

plus: why isn't typedoc calling on the --globally installed typescript instead?

**Comment by atao60** [comment]
@moshmage, have you set:

`declare var require: any;`

e.g. in an entry file with webpack.

**Comment by jan-molak** [comment]
Same problem here as well, although I can kind of get around it by ignoring the compiler errors:

```
typedoc --out ./docx/ --target ES6 --tsconfig ./tsconfig.json --exclude node_modules --ignoreCompilerErrors src/
```

**Comment by Gerrit0** [comment]
I suspect this is due to using an older version of TypeDoc than your project uses - with 0.17 TypeDoc moved to a peer dependency and this should not longer be an issue. Please open a new issue if you are having compile errors when using TypeDoc but not when compiling with tsc.
